import type { Metadata } from "next";
import { Geist, Geist_Mono, Tangerine } from "next/font/google";

import "./globals.css";
import { Providers } from "./providers";
import { Layout } from "@/components/ui/layout";
import { SplashCursor } from "@/components/animations";
// import 'uno.css'

const geistSans = Geist({
  variable: "--font-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
});

const tangerineFonts = Tangerine({
  variable: "--font-serif",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Ryland's Self Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${tangerineFonts.variable}`}
      >
        <Providers>
          <SplashCursor />
          <Layout>{children}</Layout>
        </Providers>
      </body>
    </html>
  );
}
